from __future__ import annotations

from dataclasses import dataclass
import math

from .text_engraver import FONT_NAMES, Stroke, TextEngraving, _fmt, generate_text_gcode


BORDER_STYLES = ("Rectangle", "Rounded rectangle", "Double-line", "Inset-corner", "Scallop", "Simple flourish")


@dataclass(frozen=True)
class PlaqueEngraving:
    gcode: str
    width: float
    height: float
    stroke_count: int
    strokes: tuple[Stroke, ...]


def generate_plaque_gcode(
    title: str,
    subtitle: str = "",
    *,
    subtitle_enabled: bool = True,
    title_font: str = "Simple",
    subtitle_font: str = "Simple",
    title_height: float = 10.0,
    subtitle_height: float = 5.0,
    width: float = 100.0,
    height: float = 50.0,
    margin: float = 5.0,
    border: str = "Rectangle",
    depth: float = -0.3,
    safe_z: float = 3.0,
    cut_feed: float = 300.0,
    plunge_feed: float = 100.0,
    spindle_rpm: int | None = None,
) -> PlaqueEngraving:
    if not title.strip():
        raise ValueError("Enter a plaque title")
    if title_font not in FONT_NAMES or subtitle_font not in FONT_NAMES:
        raise ValueError("Unknown engraving font")
    if border not in BORDER_STYLES:
        raise ValueError("Unknown border style")
    if not 10 <= width <= 300 or not 10 <= height <= 180:
        raise ValueError("Plaque width must be 10–300 mm and height must be 10–180 mm")
    if not 1 <= margin < min(width, height) / 2:
        raise ValueError("Margin must be at least 1 mm and leave an inner plaque area")
    if not 0.5 <= title_height <= 100 or not 0.5 <= subtitle_height <= 100:
        raise ValueError("Text height must be between 0.5 and 100 mm")
    if not -20 <= depth < 0 or not 0.1 <= safe_z <= 100:
        raise ValueError("Use a negative depth and a positive safe Z")
    if not 1 <= cut_feed <= 3000 or not 1 <= plunge_feed <= 1000:
        raise ValueError("Cut feed must be 1–3000 and plunge feed 1–1000 mm/min")
    if spindle_rpm is not None and not 1 <= spindle_rpm <= 24000:
        raise ValueError("Spindle RPM must be between 1 and 24000")

    title_layout = _layout(title, title_font, title_height)
    subtitle_layout = _layout(subtitle, subtitle_font, subtitle_height) if subtitle_enabled and subtitle.strip() else None
    # The border sits on the margin line. Keep lettering visibly inside it rather
    # than treating that line as usable text space.
    text_inset = max(1.5, min(3.0, margin / 2))
    inner_width, inner_height = width - 2 * (margin + text_inset), height - 2 * (margin + text_inset)
    if title_layout.width > inner_width + 0.001 or (subtitle_layout and subtitle_layout.width > inner_width + 0.001):
        raise ValueError("Text is too wide for the plaque; reduce text height or increase plaque width")
    occupied_height = title_layout.height + (subtitle_layout.height if subtitle_layout else 0.0)
    if occupied_height > inner_height + 0.001:
        raise ValueError("Text is too tall for the plaque; reduce text height or increase plaque height")

    strokes = list(_border_strokes(border, width, height, margin))
    title_x = (width - title_layout.width) / 2
    title_y = (height - title_layout.height) / 2 if subtitle_layout is None else height - margin - text_inset - title_layout.height
    strokes.extend(_translate(title_layout.strokes, title_x, title_y))
    if subtitle_layout:
        subtitle_x = (width - subtitle_layout.width) / 2
        subtitle_y = margin + text_inset
        if subtitle_y + subtitle_layout.height > title_y - 0.5:
            raise ValueError("Title and subtitle overlap; increase plaque height or reduce text size")
        strokes.extend(_translate(subtitle_layout.strokes, subtitle_x, subtitle_y))

    commands = [
        "; Generated by Pine Plaque Builder",
        f"; {width:g} x {height:g} mm, {border}, depth {depth:g} mm",
        "G21", "G17", "G90", "G94",
    ]
    if spindle_rpm is not None:
        commands.append(f"M3 S{spindle_rpm}")
    commands.append(f"G0 Z{safe_z:g}")
    for stroke in strokes:
        first = stroke[0]
        commands.extend((f"G0 X{_fmt(first[0])} Y{_fmt(first[1])}", f"G1 Z{depth:g} F{plunge_feed:g}"))
        commands.extend(f"G1 X{_fmt(x)} Y{_fmt(y)} F{cut_feed:g}" for x, y in stroke[1:])
        commands.append(f"G0 Z{safe_z:g}")
    commands.extend((f"G0 Z{safe_z:g}", "G0 X0 Y0", "M5", "M2"))
    return PlaqueEngraving("\n".join(commands) + "\n", width, height, len(strokes), tuple(strokes))


def _layout(text: str, font: str, text_height: float) -> TextEngraving:
    return generate_text_gcode(text, font=font, text_height=text_height, depth=-0.1, safe_z=1, cut_feed=100, plunge_feed=50)


def _translate(strokes: tuple[Stroke, ...], x_offset: float, y_offset: float) -> list[Stroke]:
    return [tuple((x + x_offset, y + y_offset) for x, y in stroke) for stroke in strokes]


def _border_strokes(style: str, width: float, height: float, margin: float) -> tuple[Stroke, ...]:
    x0, y0, x1, y1 = margin, margin, width - margin, height - margin
    rectangle: Stroke = ((x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0))
    if style == "Rectangle":
        return (rectangle,)
    if style == "Double-line":
        inset = min(2.0, margin / 2)
        return (rectangle, ((x0 + inset, y0 + inset), (x1 - inset, y0 + inset), (x1 - inset, y1 - inset), (x0 + inset, y1 - inset), (x0 + inset, y0 + inset)))
    if style == "Rounded rectangle":
        radius = min(4.0, (x1 - x0) / 5, (y1 - y0) / 5)
        return (_rounded_rect(x0, y0, x1, y1, radius),)
    if style == "Inset-corner":
        cut = min(5.0, (x1 - x0) / 5, (y1 - y0) / 5)
        return (((x0 + cut, y0), (x1 - cut, y0), (x1, y0 + cut), (x1, y1 - cut), (x1 - cut, y1), (x0 + cut, y1), (x0, y1 - cut), (x0, y0 + cut), (x0 + cut, y0)),)
    if style == "Scallop":
        return (_scallop_rect(x0, y0, x1, y1, min(3.0, margin / 2)),)
    flourish = min(5.0, margin)
    return (rectangle, ((x0, y0 + flourish), (x0 + flourish * .3, y0 + flourish * .3), (x0 + flourish, y0)), ((x1 - flourish, y1), (x1 - flourish * .3, y1 - flourish * .3), (x1, y1 - flourish)))


def _rounded_rect(x0: float, y0: float, x1: float, y1: float, r: float) -> Stroke:
    points: list[tuple[float, float]] = [(x0 + r, y0), (x1 - r, y0)]
    corners = ((x1 - r, y0 + r, -math.pi / 2), (x1 - r, y1 - r, 0), (x0 + r, y1 - r, math.pi / 2), (x0 + r, y0 + r, math.pi))
    for corner_index, (cx, cy, start) in enumerate(corners):
        points.extend((cx + r * math.cos(start + i * math.pi / 8), cy + r * math.sin(start + i * math.pi / 8)) for i in range(1, 5))
        if corner_index == 0: points.append((x1, y1 - r))
        elif corner_index == 1: points.append((x0 + r, y1))
        elif corner_index == 2: points.append((x0, y0 + r))
    return tuple(points)


def _scallop_rect(x0: float, y0: float, x1: float, y1: float, amplitude: float) -> Stroke:
    points: list[tuple[float, float]] = []
    for index in range(17):
        t = index / 16
        points.append((x0 + (x1 - x0) * t, y0 + abs(math.sin(t * math.pi * 8)) * amplitude))
    for index in range(1, 17):
        t = index / 16
        points.append((x1 - abs(math.sin(t * math.pi * 8)) * amplitude, y0 + (y1 - y0) * t))
    for index in range(1, 17):
        t = index / 16
        points.append((x1 - (x1 - x0) * t, y1 - abs(math.sin(t * math.pi * 8)) * amplitude))
    for index in range(1, 17):
        t = index / 16
        points.append((x0 + abs(math.sin(t * math.pi * 8)) * amplitude, y1 - (y1 - y0) * t))
    return tuple(points)
