"""Planar STEP-to-G-code generation for bounded 2.5D machining."""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable

from shapely.geometry import GeometryCollection, LineString, MultiLineString, MultiPolygon, Polygon
from shapely.ops import unary_union

from .step_geometry import Point2D, PlanarLoop, StepPlanarModel
from .text_engraver import Stroke, _fmt


STEP_MODES = ("Engraving", "Outside contour", "Inside contour", "Pocket", "Hole")
STEP_ORIENTATIONS = ("Top (XY)", "Top (YX)")
STEP_ZERO_LOCATIONS = ("Lower-left", "Center")


@dataclass(frozen=True)
class StepMachining:
    gcode: str
    mode: str
    width: float
    height: float
    stock_width: float
    stock_height: float
    tool_diameter: float
    depth: float
    passes: int
    stroke_count: int
    strokes: tuple[Stroke, ...]


def generate_step_gcode(
    model: StepPlanarModel,
    *,
    mode: str = "Engraving",
    orientation: str = "Top (XY)",
    stock_width: float | None = None,
    stock_height: float | None = None,
    zero_location: str = "Lower-left",
    tool_diameter: float = 3.175,
    depth: float = -0.5,
    passes: int = 1,
    safe_z: float = 3.0,
    cut_feed: float = 300.0,
    plunge_feed: float = 100.0,
    spindle_rpm: int | None = None,
) -> StepMachining:
    _validate_settings(model, mode, orientation, zero_location, tool_diameter, depth, passes, safe_z, cut_feed, plunge_feed, spindle_rpm)
    loops = tuple(_transform_loop(loop, orientation) for loop in model.loops)
    loop_bounds = _loop_bounds(loops)
    model_width, model_height = loop_bounds[4], loop_bounds[5]
    resolved_stock_width = float(stock_width) if stock_width is not None else model_width + tool_diameter
    resolved_stock_height = float(stock_height) if stock_height is not None else model_height + tool_diameter
    if resolved_stock_width <= 0 or resolved_stock_height <= 0:
        raise ValueError("Stock width and height must be greater than zero")
    if resolved_stock_width < model_width - 0.001 or resolved_stock_height < model_height - 0.001:
        raise ValueError("Stock must be at least as large as the imported top-face geometry")

    offset_x = 0.0 if zero_location == "Lower-left" else (resolved_stock_width - model_width) / 2
    offset_y = 0.0 if zero_location == "Lower-left" else (resolved_stock_height - model_height) / 2
    loops = tuple(_translate_loop(loop, offset_x, offset_y) for loop in loops)
    region = _even_odd_region(loops)
    strokes = _toolpaths(model, loops, region, mode, tool_diameter)
    if not strokes:
        raise ValueError(f"No usable {mode.lower()} toolpath could be generated from the imported geometry")
    _validate_strokes_inside_stock(strokes, resolved_stock_width, resolved_stock_height)

    commands = [
        "; Generated by TTC 3018 STEP 2.5D Machining",
        f"; Mode {mode}, tool {tool_diameter:g} mm, depth {depth:g} mm, passes {passes}",
        f"; Stock {resolved_stock_width:g} x {resolved_stock_height:g} mm, zero {zero_location}",
        "G21", "G17", "G90", "G94",
    ]
    if spindle_rpm is not None:
        commands.append(f"M3 S{spindle_rpm}")
    commands.append(f"G0 Z{safe_z:g}")
    for pass_index in range(1, passes + 1):
        pass_depth = depth * pass_index / passes
        for stroke in strokes:
            first = stroke[0]
            commands.extend((f"G0 X{_fmt(first[0])} Y{_fmt(first[1])}", f"G1 Z{_fmt(pass_depth)} F{plunge_feed:g}"))
            commands.extend(f"G1 X{_fmt(x)} Y{_fmt(y)} F{cut_feed:g}" for x, y in stroke[1:])
            commands.append(f"G0 Z{safe_z:g}")
    commands.extend((f"G0 Z{safe_z:g}", "G0 X0 Y0", "M5", "M2"))
    return StepMachining(
        "\n".join(commands) + "\n",
        mode,
        model_width,
        model_height,
        resolved_stock_width,
        resolved_stock_height,
        tool_diameter,
        depth,
        passes,
        len(strokes),
        tuple(strokes),
    )


def _validate_settings(
    model: StepPlanarModel,
    mode: str,
    orientation: str,
    zero_location: str,
    tool_diameter: float,
    depth: float,
    passes: int,
    safe_z: float,
    cut_feed: float,
    plunge_feed: float,
    spindle_rpm: int | None,
) -> None:
    if not model.loops:
        raise ValueError("The imported model contains no planar loops")
    if mode not in STEP_MODES:
        raise ValueError("Unknown STEP machining mode")
    if orientation not in STEP_ORIENTATIONS:
        raise ValueError("Unknown STEP orientation")
    if zero_location not in STEP_ZERO_LOCATIONS:
        raise ValueError("Unknown work-zero location")
    if not 0.1 <= tool_diameter <= 20:
        raise ValueError("Tool diameter must be between 0.1 and 20 mm")
    if not -20 <= depth < 0:
        raise ValueError("Machining depth must be below work Z0 and no deeper than 20 mm")
    if not isinstance(passes, int) or not 1 <= passes <= 100:
        raise ValueError("Depth passes must be a whole number from 1 to 100")
    if not 0.1 <= safe_z <= 100:
        raise ValueError("Safe Z must be between 0.1 and 100 mm")
    if not 1 <= cut_feed <= 3000 or not 1 <= plunge_feed <= 1000:
        raise ValueError("Cut feed must be 1–3000 and plunge feed 1–1000 mm/min")
    if spindle_rpm is not None and not 1 <= spindle_rpm <= 24000:
        raise ValueError("Spindle RPM must be between 1 and 24000")


def _transform_loop(loop: PlanarLoop, orientation: str) -> PlanarLoop:
    if orientation == "Top (XY)":
        return loop
    return PlanarLoop(tuple(Point2D(point.y, point.x) for point in loop.points))


def _translate_loop(loop: PlanarLoop, offset_x: float, offset_y: float) -> PlanarLoop:
    return PlanarLoop(tuple(Point2D(point.x + offset_x, point.y + offset_y) for point in loop.points))


def _loop_bounds(loops: Iterable[PlanarLoop]) -> tuple[float, float, float, float, float, float]:
    points = [point for loop in loops for point in loop.points]
    min_x = min(point.x for point in points)
    min_y = min(point.y for point in points)
    max_x = max(point.x for point in points)
    max_y = max(point.y for point in points)
    return min_x, min_y, max_x, max_y, max_x - min_x, max_y - min_y


def _even_odd_region(loops: Iterable[PlanarLoop]):
    region = GeometryCollection()
    for loop in loops:
        polygon = Polygon((point.x, point.y) for point in loop.points)
        if polygon.is_empty or polygon.area <= 1e-7:
            continue
        region = region.symmetric_difference(polygon)
    return region.buffer(0)


def _toolpaths(model: StepPlanarModel, loops: tuple[PlanarLoop, ...], region, mode: str, tool_diameter: float) -> list[Stroke]:
    if mode == "Engraving":
        return [_loop_stroke(loop) for loop in loops]
    radius = tool_diameter / 2
    if mode == "Outside contour":
        return _strokes_from_geometry(region.buffer(radius, join_style=2).boundary)
    if mode == "Inside contour":
        return _strokes_from_geometry(region.buffer(-radius, join_style=2).boundary)
    if mode == "Pocket":
        return _pocket_strokes(region, radius, tool_diameter)
    if mode == "Hole":
        return _hole_strokes(loops, tool_diameter)
    return []


def _pocket_strokes(region, radius: float, tool_diameter: float) -> list[Stroke]:
    current = region.buffer(-radius, join_style=2)
    strokes: list[Stroke] = []
    stepover = max(0.25, tool_diameter * 0.7)
    for _index in range(500):
        if current.is_empty:
            break
        strokes.extend(_strokes_from_geometry(current.boundary))
        current = current.buffer(-stepover, join_style=2)
    return strokes


def _hole_strokes(loops: tuple[PlanarLoop, ...], tool_diameter: float) -> list[Stroke]:
    if len(loops) < 2:
        raise ValueError("Hole mode requires at least one inner circular loop")
    strokes: list[Stroke] = []
    tool_radius = tool_diameter / 2
    outer = max(loops, key=lambda loop: loop.area)
    for loop in loops:
        if loop is outer:
            continue
        polygon = Polygon((point.x, point.y) for point in loop.points)
        circularity = 4 * math.pi * polygon.area / max(polygon.length * polygon.length, 1e-9)
        if circularity < 0.88:
            raise ValueError("Hole mode supports circular inner loops only")
        radius = math.sqrt(polygon.area / math.pi) - tool_radius
        if radius <= 0.05:
            raise ValueError("An imported hole must be larger than the selected tool diameter")
        center = polygon.centroid
        strokes.append(tuple((center.x + radius * math.cos(index * math.tau / 48), center.y + radius * math.sin(index * math.tau / 48)) for index in range(49)))
    return strokes


def _loop_stroke(loop: PlanarLoop) -> Stroke:
    first = loop.points[0]
    return tuple((point.x, point.y) for point in loop.points + (first,))


def _strokes_from_geometry(geometry) -> list[Stroke]:
    if geometry.is_empty:
        return []
    if isinstance(geometry, Polygon):
        strokes = [_ring_stroke(geometry.exterior)]
        strokes.extend(_ring_stroke(ring) for ring in geometry.interiors)
        return strokes
    if isinstance(geometry, MultiPolygon):
        return [stroke for polygon in geometry.geoms for stroke in _strokes_from_geometry(polygon)]
    if isinstance(geometry, LineString):
        return [_line_stroke(geometry)]
    if isinstance(geometry, MultiLineString):
        return [_line_stroke(line) for line in geometry.geoms]
    if isinstance(geometry, GeometryCollection):
        return [stroke for item in geometry.geoms for stroke in _strokes_from_geometry(item)]
    return []


def _ring_stroke(ring) -> Stroke:
    return tuple((float(x), float(y)) for x, y in ring.coords)


def _line_stroke(line: LineString) -> Stroke:
    return tuple((float(x), float(y)) for x, y in line.coords)


def _validate_strokes_inside_stock(strokes: Iterable[Stroke], width: float, height: float) -> None:
    for stroke in strokes:
        for x, y in stroke:
            if x < -0.001 or y < -0.001 or x > width + 0.001 or y > height + 0.001:
                raise ValueError("Generated toolpath extends outside the declared stock")
